# services
services:
  api-gateway:
    build: ./tlpservices/api-gateway
    image: api-gateway
    ports:
      - 8080:8080
    env_file: .env

  identity-service:
    build: ./tlpservices/identity-service
    depends_on:
      api-gateway:
        condition: service_started
    image: identity-service
    ports:
      - 5600:5600
    env_file: .env

  patient-service:
    build: ./tlpservices/patient-service
    depends_on:
      api-gateway:
        condition: service_started
    image: patient-service
    volumes:
      - ./var/logs:/var/logs
    ports:
      - 5610:5610
    env_file: .env

  integration-service:
    build: ./tlpservices/ghl-service
    depends_on:
      api-gateway:
        condition: service_started
    image: integration-service
    ports:
      - 5620:5620
    env_file: .env

  webhook-service:
    build: ./tlpservices/webhook-service
    depends_on:
      api-gateway:
        condition: service_started
    image: webhook-service
    volumes:
      - ./var/logs:/var/logs
    ports:
      - 5670:5670
    env_file: .env

  monitor-service:
    build: ./tlpservices/monitor-service
    depends_on:
      api-gateway:
        condition: service_started
    image: monitor-service
    volumes:
      - ./var/logs:/var/logs
    ports:
      - 5680:5680
    env_file: .env

  notification-service:
    build: ./tlpservices/notification-service
    depends_on:
      api-gateway:
        condition: service_started
    image: notification-service
    volumes:
      - ./var/logs:/var/logs
    ports:
      - 5640:5640
    env_file: .env

  config-service:
    build: ./tlpservices/config-service
    depends_on:
      api-gateway:
        condition: service_started
    image: config-service
    ports:
      - 5650:5650
    env_file: .env

  embodi-client:
    build: ./tlpservices/embodi-client
    depends_on:
      api-gateway:
        condition: service_started
      identity-service:
        condition: service_started
      integration-service:
        condition: service_started

    image: embodi-client
    volumes:
      - ./var/logs:/var/logs
    ports:
      - 5690:5690
    env_file: .env
# disk volumes
