version: "3.7"

services:
  tlp-server:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    restart: unless-stopped

volumes:
  mongo-data:
