connection:
  url: localhost
  port: 5665
  
clients:
  - name: Demo Client
    location: FirstLocation
    secret: thisismysecret

  - name: Silkone Two
    location: SecondLocation
    secret: thisisanothersecret
